### ISSUE TITLE
On stage @ Try!Swift Conf

### ISSUE THREAD

**Issue by matteocrippa** [qutheory/vapor#105]
I know it's not a really issue but you  got just mentioned during try!Swift 2016 conf in Tokyo during a speech by @cjwirth

**Comment by ketzusaka** [comment]
👍🏻👍🏻😬

**Comment by tannernelson** [comment]
Sweet :) What did they say?

**Comment by matteocrippa** [comment]
You got mentioned with Kitura and Perfect as way to setup web based apps in swift

**Comment by cjwirth** [comment]
Hey! I'm the one who gave the talk! My slides are [here](https://github.com/cjwirth/trySwiftServer/tree/master/Slides) if you're interested.

I was looking at libraries for web servers in Swift, with Perfect and Kitura as the big ones that everyone knows.

I also spent a good amount of time looking at Vapor during my preparation. The way it's designed is pretty similar to the way I would have written a library like this if I were to do it. So that's where the shout out came from :smile:

**Comment by matteocrippa** [comment]
@cjwirth thank you again for you talk, It was for me the right topic in the right moment. I was trying to play with some server side libs to port a node.js backend I developed so far! 
Great talk and hope to see you again for 2017 conf here in Tokyo

**Comment by tannernelson** [comment]
Thanks @cjwirth!
