### ISSUE TITLE
Error receiving request: InvalidRequestLine

### ISSUE THREAD

**Issue by ketzusaka** [qutheory/vapor#190]
We're seeing some reports of this error. We're looking into it.

**Comment by czechboy0** [comment]
From a quick debugging session, it seems like instead of the request handling code to run once, it's called twice. The first time the request is properly processed, the second time there's no data to be read so the HTTP request header fails to be parsed. Afterwards the server seems to crash.

The question is why the server is accepting one TCP connection twice.

**Comment by ketzusaka** [comment]
Is the server actually crashing? It should just be throwing, and as long as you're not `try!`ing it should be fine.

**Comment by ketzusaka** [comment]
The server crashing was unrelated to this error. This error is caused by us trying to parse a signal from the remote peer that they are closing the connection. We've updated Hummingbird to throw an error in `receive` in this situation, and Vapor will handle the error specially instead of printing a scary message.
