### ISSUE TITLE
Suggestion for addition features to roadmap

### ISSUE THREAD

**Issue by wildfiremedia** [qutheory/vapor#203]
Vapor need to be reactive or could integrate Vue.js that has works on Laravel and Meteor.js.

Faker data for unit testing

VaporChannel for video tutorials and discussion

Are there any performance improvement if we compile vapor with -fast0 ?

**Comment by tannernelson** [comment]
These are great additions. http://qutheory.io is actually running using Vapor + Vue. It's a great combo.

I'll add these to the roadmap.

**Comment by wildfiremedia** [comment]
Nice surprise! And I hope the benchmark will indicate CPU usage and memory consumption for a comprehensive comparison, I need to convince my team to adopt Vapor or Node.js in the near future and yet Node.js 6.0 has boosted its performance recently. I would love to see how its stack up again JS.

**Comment by ketzusaka** [comment]
I believe you'd see better performance in Vapor over anything in JS. Swift is a very fast language, and JS is a very slow one.

**Comment by tannernelson** [comment]
The benchmarks I completed (which I hope to release soon) simply show requests/second. We blow any PHP, Ruby, etc out of the water. And we are head to head against Node.js. Node is surprisingly fast given it's JavaScript. I believe it's because a lot of their core is written in C. I'm sure Node apps start to slow down as the application gets heavier in JS.

Either way, if we're already head to head with Node.js this early in the game, I have really high hopes for beating them by good margins when we start spending time actually optimizing the framework.

**Comment by wildfiremedia** [comment]
Thanks, and probably it's a good time to integrate Venice if it could brings extra boost? 
https://github.com/VeniceX/Venice

**Comment by tannernelson** [comment]
Venice is S4 compatible so Vapor should already work with that. If it's considerably faster, we could consider bringing it in as the default server.

**Comment by tannernelson** [comment]
These items have been added. Let me know if you come up with any more ideas, thanks!
