### ISSUE TITLE
Send Email

### ISSUE THREAD

**Issue by LoganWright** [qutheory/vapor#277]
# Send Email

* Author(s): [Developer](https://github.com/loganwright)

## Introduction

A simple way to send basic emails from the server.

## Motivation

Building modern apis often requires interacting with users' email addresses for things like password recovery, authentication verification, and general communication.

## Proposed solution

Implement a basic configurable email send behavior

## Code snippets

More research required for suggested syntax

## Impact

New feature, impact will be minimal.

## Alternatives considered

Just using HTTPClient w/ MailChimp or some other exposed email send api

**Comment by Joannis** [comment]
HTTPClient communicating with MailChimp would be more easily achievable and I would personally love it if this existed. But I think using MailChimp with their HTTP API is completely different from sending emails using SMTP.

I would prefer supporting both MailChimp as well as SMTP. But they're not comparible methods or even worth considering an alternative for one another. But making these two separate issues (the alternative and the main proposed solution) would be fine.

That said.. I think SMTP is an essential part of a web framework.

**Comment by LoganWright** [comment]
@Joannis Great feedback, I think a good path for us would be to investigate the complexity of smtp, perhaps we can make mailchimp easy in the interim, but I would also prefer smtp directly over reliance on a paid service.

**Comment by tannernelson** [comment]
We could consider http://www.mailgun.com

**Comment by mpclarkson** [comment]
I recommend https://www.sparkpost.com/pricing - it's totally free for **100,000** emails per month. It is the service that Mailchimp recommended when they shut down Mandrill.

**Comment by NathanFlurry** [comment]
Users don't want to use a 3rd party service to do this for them. They're using Vapor because they want to do everything themselves; if they wanted a solution that did everything for them and took control out of their hands, they'd be using something like Firebase.

I think our best bet is to create a wrapper for a C mailing library. After some (very) brief research, it looks like these are our best bets: _(I haven't researched the licenses on there.)_
* (libmail)[https://sourceforge.net/projects/libmail/]
* (libquickmail)[https://sourceforge.net/projects/libquickmail/]
* (libcurl)[https://curl.haxx.se/libcurl/]

**Comment by tannernelson** [comment]
What's important here is the protocol we make for sending mail. Behind that, any of these implementations could power it. I would start with the simplest one first which looks like Mailgun. That doesn't require any C dependencies and has a well documented API.

After that, it's easy to make other drivers.

**Comment by tannernelson** [comment]
This depends on #262.

**Comment by LoganWright** [comment]
I'm very pleased to say that we have merged the first Pure Swift SMTP Library 👍 It'll be in next merge.

https://github.com/qutheory/engine#smtp-1
