### ISSUE TITLE
JSON encoded requests

### ISSUE THREAD

**Issue by tannernelson** [qutheory/vapor#28]
Support JSON encoded requests

**Comment by czechboy0** [comment]
I'd like to humbly point out that I wrote a pure Swift JSON parser for exactly the purpose of using it in my server apps. Parsing seems to work well and is pretty well tested. Serialization into data is finished on a branch, but I'm resolving some final issues. 

TL;DR feel free to use it as a dependency to add request parsing from JSON to Vapor (that's already working and tested). Serialization into data will be arriving next week in a new version. 

https://github.com/czechboy0/Jay

**Comment by czechboy0** [comment]
I also noticed that in your manual JSON serializer you're not correctly handling escaping. All that is handled and tested in Jay.

**Comment by tannernelson** [comment]
So your JSON parser will be able to take a native Swift Dictionary or Array (`Any`) and convert it into a String?

Example:
```swift

let data = [
  "test": [
    "number": 1,
    "string": "abc",
    "double": 3.14,
    "nest": [
      1, 2, 3
    ]
  ]
  ...etc
]

let jsonString: String = YourParser.parse(data)
```

If your library does this properly on Linux, then I would love to use it ASAP. The `JSONSerializer` class I wrote was last ditch effort to get some sort of JSON support working on Linux.

**Comment by czechboy0** [comment]
Yes exactly. Parsing JSON from data is already released, this JSON object to data serialization I worked and figured out today, it's on a branch. Take a look at the link above, I comment heavily so it should be understandable. 

Makes me think - if you have any specific examples of payloads you want to make sure get encoded properly, PR a new test in Jay so that I can add it to the core tests and we can make sure it all keeps working just as expected going forward. 

I'm AFK over the weekend, so it might be a good time to add parsing of JSON requests to Vapor, and once I finish the serialization early next week, I'll let you know that there's a tested version ready.

How does that sound?

**Comment by tannernelson** [comment]
Busy this weekend as well, so I don't know if I will get around to JSON parsing. But as soon as serializing is available let me know. That's a big hold up for Vapor right now.

**Comment by czechboy0** [comment]
Sounds good. The parsing API will not change, but if you want to wait for the full package, I'll let you know once I'm confident it works well. 

Also - I'll use the above example as a parsing test so that I can make sure you're getting what you need.

**Comment by tannernelson** [comment]
Sounds great. Let me know if you need any assistance/feel free to join the Slack mentioned on Vapor's readme.

**Comment by LoganWright** [comment]
There are also potential suggestions here: https://github.com/tannernelson/vapor/issues/22

Those use PureJsonSerializer which I'm partial to, but don't feel too strongly about

**Comment by tannernelson** [comment]
Added to roadmap.
