### ISSUE TITLE
Change router syntax a tiny bit for more clarity

### ISSUE THREAD

**Issue by Evertt** [qutheory/vapor#325]
I don't want to write a whole formal proposal for this, since it's fairly simple. Say I have this in my router:

```swift
app.grouped("users") { users in
    users.get("/") { request in
        // do something here to respond to `GET /users`
    }

    users.post("/") { request in
        // do something here to respond to `POST /users`
    }
}
```

I find the slash a tiny bit confusing and it takes me a few seconds to process and conclude "ah yes the slash doesn't add anything, we're still just talking about `/users` and nothing after that". So I would like to propose that we make the slash optional. As in, if you don't provide a path then the slash is implied. That would turn the above code into:

```swift
app.grouped("users") { users in
    users.get { request in
        // do something here to respond to `GET /users`
    }

    users.post { request in
        // do something here to respond to `POST /users`
    }
}
```

Which I find much more clear. And of course in other situations writing the slash explicitly would *add* to clarity. For example when you're writing a route for the homepage.

```swift
app.get("/") { request in
    return try app.view("welcome.html")
}
```

Which is still possible, because this proposal just adds a choice, nothing else.

**Comment by tannernelson** [comment]
I like this idea.

**Comment by Evertt** [comment]
Oh and I don't understand how the code generator works in swift, so either someone else implements this or someone could explain me a bit how the code generator works and then I implement it. :-)

**Comment by tannernelson** [comment]
In Xcode, you run the `Generator` project and it should output the generated file in the appropriate path.

**Comment by Evertt** [comment]
Okay and I have a little addition, what do you think about this @tannernelson ?

Right now I believe it's only possible to group routes by string or by middleware. It would also be nice to group routes by `StringInitializable`, don't you think? Then you could do this:

```swift
app.grouped("users") { users in
    users.get { request in
        // do something here to respond to `GET /users`
    }

    users.post { request in
        // do something here to respond to `POST /users`
    }

    users.grouped(User) { user in
        user.get { request, user in
            // do something here to respond to `GET /users/:id`
        }

        user.put { request, user in
            // do something here to respond to `PUT /users/:id`
        }
    }
}
```

I'm not sure if this is the best example, but oh well...

**Comment by tannernelson** [comment]
If String works, `StringInitializable` should also work. Makes sense to me.

**Comment by Evertt** [comment]
Making it work with `StringInitializable` is a bit more complicated than I thought. @LoganWright would you like to implement that? I believe you'll know better how to best to that than I.

I already made a branch called `tiny-router-improvement` which contains the change I proposed in my original post.

**Comment by LoganWright** [comment]
This looks great to me, I think we can definitely remove the `("/")` requirement, it looks great. Might be as simple as `= "/"` for an empty call.

For the grouping by `StringInitializable`, I think we should move that discussion to a separate thread since it poses considerably more difficulty. The main issue is constructing the closures. For example, we can chain strings/middleware because they don't affect closures at all. However, the number of string initializable arguments directly affects the number of arguments so we'd need a scheme where if you have:

```
app.grouped(Int.self) { group in 
    group.get { request, int in // how do we know that this get method has 2 arguments?
```

I have messed around with composition utilizing tuples, but it's currently not a really viable option. I think for now, we will likely have to postpone grouping typesafe routes until greater generic support is added. I'd personally love to have this as a feature.
