### ISSUE TITLE
Couldn't start server on Xcode 

### ISSUE THREAD

**Issue by sanskarvihin** [qutheory/vapor#343]
I build server Xcode project for server but Whenever I run it, it throws,

[1464768679] [WARNING] Could not open file ./Resources/Views/Includes/header.mustache. Error: CouldNotOpenFile
[1464768679] [INFO] Server starting ...
[1464768679] [ERROR] Server start error: bindingFailed(13, Optional("Permission denied"))
Program ended with exit code: 0

**Comment by LoganWright** [comment]
@sanskarvihin the issue is its defaulting to port 80 which you don't have permission. We moved some stuff around and it's harder to set port now. We're in the process of simplifying it and helping w/ tooling for now, in Xcode

1. Edit your scheme

<img width="174" alt="screen shot 2016-06-01 at 10 12 52 am" src="https://cloud.githubusercontent.com/assets/5750489/15712784/a2addc0a-27e1-11e6-9838-d5a6435dda32.png">

2. Select Arguments Tab

<img width="312" alt="screen shot 2016-06-01 at 10 13 02 am" src="https://cloud.githubusercontent.com/assets/5750489/15712789/ab5e4fc4-27e1-11e6-86a0-4ece3df93a28.png">

3. Add argument `--port=8080`

<img width="766" alt="screen shot 2016-06-01 at 10 13 20 am" src="https://cloud.githubusercontent.com/assets/5750489/15712796/b64e6342-27e1-11e6-97e7-2c59daea0cba.png">

I'll leave this open as a reminder until we get a better way

**Comment by tannernelson** [comment]
> Could not open file ./Resources/Views/Includes/header.mustache. Error: CouldNotOpenFile

You need to update your working directory in Xcode. Go to Schemes > Edit Scheme > Run > Options > Working Directory > Use Custom Working Directory and set the Working Directory to be the root of your project.

<img width="259" alt="screen shot 2016-06-01 at 10 14 32 am" src="https://cloud.githubusercontent.com/assets/1342803/15712788/a7842bc6-27e1-11e6-84ee-aa541a2130d3.png">

> Server start error: bindingFailed(13, Optional("Permission denied"))

Do what @LoganWright said or also you can change which port is used by default if you have `Config/app.json` and `{ "port": 8080 }`

**Comment by LoganWright** [comment]
Vapor now defaults to `8080` with the assumption that most production servers will specify a port, and in the interim it makes quickstart smoother.
