### ISSUE TITLE
Problems compiling a fresh project

### ISSUE THREAD

**Issue by frankieleef** [qutheory/vapor#440]
I just created a new Vapor project and tried to compile it, but unfortunately it's failing. I'm using Swift version **3.0-dev** and Vapor CLI version **0.5.3**. I'm getting the following errors:

> error: cannot convert value of type '(arg: UnsafeMutablePointer<Void>) -> UnsafeMutablePointer<Void>?' to expected argument type '(@convention(c) (UnsafeMutablePointer<Void>?) -> UnsafeMutablePointer<Void>?)!'
                guard pthread_create(&pt, nil, runner, pointer) == 0 && pt != nil else {
                                               ^~~~~~

> :35:48: error: extraneous argument label 'options:' in call
                return self.base64EncodedString(options: .lineLength64Characters)
                                               ^~~~~~~~~~

> :73: error: extraneous argument label 'options:' in call
                    return NSData(bytes: bytesArray).base64EncodedString(options: [])
                                                                        ^~~~~~~~~~

Because I don't have any experience with Swift I'm not able to figure out what's going wrong exactly. but hopefully I gave you enough information to see what's going wrong.

**Comment by woolsweater** [comment]
I was struggling with this as well yesterday. It looks like all the dominoes have to be lined up perfectly at first or it will not succeed. `vapor clean` is available to try to restore things, but with a brand new project blowing it away and re-cloning may be the easiest option.

First, the Swift that's used to build must -- at the moment -- be the 2016-06-06 dev snapshot. This is changing frequently, from what I've read. I'm using [swiftenv](https://github.com/kylef/swiftenv), which was recommended in [one of the tutorials](https://medium.com/@timominous/basic-swift-server-setup-using-vapor-475b10e811b7#.bgl9v3hj0), to manage this. You can also set the Swift version in Xcode, via the Toolchains item in the Xcode menu.

Next, the other tools must be the Xcode 7.3.1 versions. This is settable in Xcode Preferences > Locations > Command Line Tools, or on the command line using `xcode-select -s /Applications/Xcode.app` (and you'll be told you need to `sudo` that).

Despite what the ["Current Environment"](https://github.com/qutheory/vapor#-current-environment) section in the README says, this is the only way I could get the sample project to build.

You'll get different compilation errors for different Swift versions, because the standard lib/Foundation are changing often, and again, what I've said here may become out-of-date the next time changes happen to any of the involved projects.

**Comment by alexdoloz** [comment]
I have the same problem. I could fix 2 last issues but don't understand what to do with the first one.

**Comment by LoganWright** [comment]
@alexdoloz @frankieleef 

Does this Q&A help? 

http://stackoverflow.com/questions/38296145/vapor-web-framework-error-swift-does-not-support-the-sdk-macosx10-11-sdk

**Comment by alexdoloz** [comment]
@LoganWright 
Thank you, this was helpful. My mistakes: 1. I used Xcode 7 instead of Xcode 8 beta. 2. I used toolchain with date 06.06 instead of 21.06. Now I can compile the project.

**Comment by frankieleef** [comment]
@LoganWright 

This was helpful, thanks!

For feature reference: If you ever experience this issue it's luckily a pretty easy fix. First of all, make sure you use [swiftenv](https://github.com/kylef/swiftenv), this will make life a lot easier. After that, make sure you install the [Xcode 8 beta](https://developer.apple.com/xcode/) version. Also, make sure you have the right snapshot installed. You can do this by checking your .swift-version file and then use `swiftenv install {SNAPSHOT}`. After installing, also make sure you're using it globally by running `swiftenv global {SNAPSHOT}`. If you're getting an SDK error, just run  `sudo xcode-select -s /Applications/Xcode-beta.app/`. This should fix all your issues and you should be able to build.

**Comment by LoganWright** [comment]
Closing this as resolved, feel free to reopen if more problems come up 👍
