### ISSUE TITLE
Problem with swiftpm

### ISSUE THREAD

**Issue by sigge75** [qutheory/vapor#93]
I got an error `NoSources` when `swift build`ing on Ubuntu 15 server (swift dev-snapshot from Feb 25).

To make it work I had to:
```bash
cd Packages/Vapor-0.2.6/Vapor
mv */* .
rmdir * # for good measure
```

**Comment by tannernelson** [comment]
Was this when running the vapor example project? Make sure to use the `./run` script included for the time being. We have a PR open with Swift PM to fix this.

**Comment by sdbip** [comment]
No, not the example project. I tried to create my own from scratch. I deleted the `Packages/Vapor-0.2.6/Tests/` folder manually before building. That's all the run script does, right?

`swift build` still does not find any .swift files because they are organized into subfolders under the `Vapor` target (`Packages/Vapor-0.2.6/Vapor/`). To make swiftpm find them, I moved them out of the subfolders with the `mv` command above.
